services:
  postgres:
    image: postgres:15.8-alpine3.20
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "54320:5432"
    volumes:
      - ./deploy/postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: