services:
  postgres:
    image: postgres:15.8-alpine3.20
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ./deploy/postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: deploy/opt.Dockerfile
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - postgres
volumes:
  postgres_data: